"""Shared data contracts for sessions and the Chat, Code, Fix, and Memory stages."""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any, Literal, TypedDict

from pydantic import BaseModel, ConfigDict, Field, field_validator


AGENT_STAGES = ("chat", "code", "fix", "memory")
CONFIRMABLE_SECTIONS = ("goal", "inputs_outputs", "constraints", "acceptance")


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


class StrictModel(BaseModel):
    """Base model that rejects undeclared fields to keep stage contracts strict."""

    model_config = ConfigDict(extra="forbid")


class InputSpec(StrictModel):
    """Describes one input required by the generated task."""

    name: str
    type: str
    source: str
    required: bool = True


class OutputSpec(StrictModel):
    """Describes one output produced by the generated task."""

    name: str
    format: str
    destination: str


class TaskSpec(StrictModel):
    """Structured task contract shared by Chat, Code, and Fix."""

    objective: str = ""
    inputs: list[InputSpec] = Field(default_factory=list)
    outputs: list[OutputSpec] = Field(default_factory=list)
    steps: list[str] = Field(default_factory=list)
    constraints: list[str] = Field(default_factory=list)
    allowed_apis: list[str] = Field(default_factory=list)
    allowed_dependencies: list[str] = Field(default_factory=lambda: ["standard-library"])
    side_effects: list[str] = Field(default_factory=list)
    acceptance_criteria: list[str] = Field(default_factory=list)
    unresolved_questions: list[str] = Field(default_factory=list)
    status: Literal["draft", "ready_for_confirmation", "confirmed"] = "draft"
    version: int = 0

    @field_validator(
        "steps",
        "constraints",
        "allowed_apis",
        "allowed_dependencies",
        "side_effects",
        "acceptance_criteria",
        "unresolved_questions",
    )
    @classmethod
    def remove_blank_items(cls, values: list[str]) -> list[str]:
        return [value.strip() for value in values if value.strip()]


class ChatDecision(StrictModel):
    """Represents Chat's extracted decisions, questions, and plan updates."""

    spec_patch: dict[str, Any] = Field(default_factory=dict)
    confirmed_sections: list[Literal["goal", "inputs_outputs", "constraints", "acceptance"]] = (
        Field(default_factory=list)
    )
    questions: list[str] = Field(default_factory=list)
    assistant_message: str = ""
    decisions: list[str] = Field(default_factory=list)
    scenario_plan: str = ""

    @field_validator("questions")
    @classmethod
    def clean_questions(cls, values: list[str]) -> list[str]:
        return [value.strip() for value in values if value.strip()]

    @field_validator("decisions")
    @classmethod
    def clean_decisions(cls, values: list[str]) -> list[str]:
        return [value.strip() for value in values if value.strip()]

    @field_validator("scenario_plan")
    @classmethod
    def clean_scenario_plan(cls, value: str) -> str:
        return value.strip()

class RetrievalQueryPlan(StrictModel):
    """Contains bounded search queries for API or SDK retrieval."""

    queries: list[str]

    @field_validator("queries")
    @classmethod
    def validate_queries(cls, values: list[str]) -> list[str]:
        cleaned = [value.strip() for value in values if value.strip()]
        if not cleaned:
            raise ValueError("At least one retrieval query is required")
        return cleaned[:4]


class FixPlan(StrictModel):
    """Describes a targeted repair and the API context needed to apply it."""

    problem: str
    location: str
    change: str
    keep_unchanged: list[str] = Field(default_factory=list)
    search_queries: list[str] = Field(default_factory=list)
    contract_compatible: bool = True

    @field_validator("search_queries")
    @classmethod
    def clean_fix_queries(cls, values: list[str]) -> list[str]:
        return [value.strip() for value in values if value.strip()][:4]


class CodeEdit(StrictModel):
    """Represents one exact old-text to new-text code edit."""

    old: str
    new: str


class CodePatch(StrictModel):
    """Carries either exact edits or a complete replacement generated by Fix."""

    edits: list[CodeEdit] = Field(default_factory=list)
    replacement_code: str = ""


class PatchReview(StrictModel):
    """Records whether a proposed code patch passed safety checks."""

    ok: bool
    checks: list[str] = Field(default_factory=list)
    problems: list[str] = Field(default_factory=list)


class ModelContextRecord(StrictModel):
    """Persists the prompts, response, and sources used for one model call."""

    stage: str
    system_prompt: str
    user_prompt: str
    response: str
    estimated_tokens: int
    sources: list[str] = Field(default_factory=list)


class CodeValidation(StrictModel):
    """Contains static validation status and diagnostics for generated code."""

    ok: bool
    errors: list[str] = Field(default_factory=list)
    imports: list[str] = Field(default_factory=list)


class RunResult(StrictModel):
    """Captures the process result from executing generated code."""

    ok: bool
    returncode: int
    stdout: str
    stderr: str
    timed_out: bool
    duration_seconds: float

class ErrorInfo(StrictModel):
    """Normalizes execution and validation failures into a stable error shape."""

    category: Literal[
        "success",
        "static_validation",
        "timeout",
        "missing_dependency",
        "missing_input",
        "syntax_error",
        "runtime_error",
    ]
    exception_type: str = ""
    message: str = ""
    traceback: str = ""


class ChatMessage(StrictModel):
    """Stores one user, assistant, or system message in a session."""

    role: Literal["user", "assistant", "system"]
    content: str
    created_at: str = Field(default_factory=utc_now)


class SessionRecord(StrictModel):
    """Durable state for a complete Chat-Code-Fix-Memory workflow."""

    session_id: str
    phase: Literal[
        "collecting_goal",
        "collecting_inputs_outputs",
        "collecting_constraints",
        "collecting_acceptance",
        "collecting_plan",
        "awaiting_confirmation",
        "generating_code",
        "executing",
        "repairing",
        "awaiting_review",
        "memory",
        "approved",
        "succeeded",
        "failed",
    ] = "collecting_goal"
    messages: list[ChatMessage] = Field(default_factory=list)
    draft_spec: TaskSpec = Field(default_factory=TaskSpec)
    confirmed_spec: TaskSpec | None = None
    confirmed_sections: list[str] = Field(default_factory=list)
    decisions: list[str] = Field(default_factory=list)
    pending_questions: list[str] = Field(default_factory=list)
    selected_scene: dict[str, Any] | None = None
    draft_plan: str = ""
    confirmed_plan: str = ""
    retrieval_queries: list[str] = Field(default_factory=list)
    retrieved_context: list[dict[str, Any]] = Field(default_factory=list)
    generated_code: str = ""
    code_validation: CodeValidation | None = None
    run_result: RunResult | None = None
    run_history: list[dict[str, Any]] = Field(default_factory=list)
    fix_attempts: int = 0
    approval_note: str = ""
    approved_scene_path: str = ""
    status: str = "chat"
    created_at: str = Field(default_factory=utc_now)
    updated_at: str = Field(default_factory=utc_now)


class OrchestratorState(TypedDict, total=False):
    """Transient graph state passed between workflow nodes."""

    event: Literal["message", "confirm", "refine"]
    user_input: str
    session: dict[str, Any]
    task_spec: dict[str, Any]
    decisions: list[str]
    scenario_plan: str
    retrieval_queries: list[str]
    retrieved_context: list[dict[str, Any]]
    fix_context: list[dict[str, Any]]
    fix_plan: dict[str, Any]
    code_patch: dict[str, Any]
    patch_review: dict[str, Any]
    patch_error: str
    previous_code: str
    context_records: list[dict[str, Any]]
    code: str
    code_validation: dict[str, Any]
    run_result: dict[str, Any]
    run_history: list[dict[str, Any]]
    fix_attempts: int
    fix_attempt_limit: int
    error_info: dict[str, Any]
    user_instruction: str
    status: str
    assistant_message: str
    artifact_paths: list[str]
